feature(#34): Implment members profile page
Dsek-LTH/member-page pull request #119
Opened 2021-04-15 16:55 UTC by LucasBoberg

Closes #34

2021-04-21 20:52 UTC, emilwihlander requested changes
Ser bra ut! Drog ner det lokalt för att se hur det såg ut, lägg gärna upp lite screenshots nästa gång du gör något grafiskt :)

Har lite små kommentarer

2021-04-21 20:52 UTC, emilwihlander commented on frontend/components/Header/index.tsx
> +            <Link href={'/members/' + data.me.student_id}>
Sektionen kan även ha medlemmar som saknar student id (hedersmedlemmar, virtuella medlem, mm.) vilket gör att det kanske är dumt att identifiera baserat på det? Id kommer alltid med säkerhet finnas och tror det är så nuvarande hemsidan gör det.

2021-04-21 20:52 UTC, emilwihlander commented on frontend/public/locales/en/member.json
> +    "memberError": "Medlem broken"
medlem broken känns svengelskt ;)

2021-04-21 20:52 UTC, emilwihlander commented on frontend/styles/articlePageStyles.tsx
> +const memberPageStyles = makeStyles(theme => ({
Detta känns inte rätt? Att det bytt namn i filen som fortfarande heter articlePageStyles?

2021-04-21 20:52 UTC, emilwihlander commented on frontend/styles/memberPageStyles.tsx
> +const articlePageStyles = makeStyles(theme => ({
...och här heter det articlePageStyles haha

2021-04-22 16:05 UTC, emilwihlander approved these changes
Snyggt!

2021-04-22 16:09 UTC, noahmay approved these changes

2021-04-22 16:09 UTC, merged