tests(#116): Add tests to calendar service
Dsek-LTH/member-page pull request #129
Opened 2021-04-28 16:32 UTC by kuleshmaria

Closes #116

2021-04-28 18:45 UTC, emilwihlander requested changes
En liten kommentar, snyggt! Saknar dock en fil som gör att testerna först automatiskt i github, se foldern `.github/workflows/` och kopiera någon av filerna för en annan service :)

2021-04-28 18:45 UTC, emilwihlander commented on backend/services/calendar/tests/event.spec.ts
> +            expect(query.sql.toLowerCase()).to.include('where')
Antar att du sett något liknande i ett test jag skrivit men det finns bättre sätt att göra detta hehe

Kolla istället att `query.bindings` (en lista av alla variabler som finns i queryn) innehåller alla de variabler som du vill filtrera på, så i detta fallet
```
expect(query.bindings).to.include(filter.start_datetime);
```

2021-04-29 15:30 UTC, kuleshmaria commented on backend/services/calendar/tests/event.spec.ts
> +            expect(query.sql.toLowerCase()).to.include('where')
Fixat!

2021-04-29 15:47 UTC, emilwihlander approved these changes

2021-04-29 15:50 UTC, merged