feature(#73) Adds creating and editing news pages
Dsek-LTH/member-page pull request #139
Opened 2021-05-05 00:02 UTC by noahmay

Adds pages for creating and editing news, See attached images. The file upload currently does nothing and is subject to change since no file server exists yet. Also implements a user provider to easily access the currently logged-in user across the app.

![screencapture-localhost-3000-news-article-edit-98-2021-05-05-01_59_35](https://user-images.githubusercontent.com/7382555/117083766-ba9afc00-ad45-11eb-9c86-c52512e40218.png)
![screencapture-localhost-3000-news-article-create-2021-05-05-01_59_56](https://user-images.githubusercontent.com/7382555/117083772-bc64bf80-ad45-11eb-99f6-e695e26515ca.png)
![screencapture-localhost-3000-news-article-create-2021-05-05-02_00_18](https://user-images.githubusercontent.com/7382555/117083767-bbcc2900-ad45-11eb-8701-b4e2c8a85b13.png)

2021-05-05 10:25 UTC, LucasBoberg commented on frontend/components/ArticleEditor/articleEditorStyles.tsx
> +}))
Behövs denna filen?

2021-05-05 10:31 UTC, LucasBoberg commented on frontend/public/locales/sv/news.json
> +    "loadingArticle": "Loading article...",
På engelska men bör vara på svenska

2021-05-05 10:32 UTC, LucasBoberg commented on frontend/public/locales/en/news.json
> +    "loadingArticle": "Laddar artikel...",
På svenska men bör vara på engelska

2021-05-05 10:32 UTC, LucasBoberg requested changes
Fixa de kommentarerna som jag har lagt

2021-05-05 12:27 UTC, noahmay commented on frontend/components/ArticleEditor/articleEditorStyles.tsx
> +}))
Nej, tänkte mest att det är nice om styles filen redan finns ifall man vill lägga till styles i framtiden. Ska jag ta bort den?

2021-05-05 13:35 UTC, LucasBoberg commented on frontend/components/ArticleEditor/articleEditorStyles.tsx
> +}))
nej lämna den då, det är sant att det gör det lättare för framtiden

2021-05-05 13:37 UTC, LucasBoberg approved these changes

2021-05-06 15:46 UTC, merged

2021-05-06 15:56 UTC, TheJarles approved these changes