feature(#188): Migrate databaase from mysql to postgres
Dsek-LTH/member-page pull request #197
Opened 2021-07-25 23:16 UTC by noahmay

Closes #188

2021-07-26 15:30 UTC, emilwihlander requested changes
Även de andra services fil med db-typer borde byta namn till database.ts och plocka bort Db från typerna.

2021-07-26 15:30 UTC, emilwihlander commented on README.md
> +Username (POSTGRES_HOST from .env)
Borde det inte vara POSTGRES_USER?

2021-07-26 21:17 UTC, noahmay commented on README.md
> +Username (POSTGRES_HOST from .env)
Det borde det absolut vara. Fixar.

2021-07-27 22:44 UTC, emilwihlander approved these changes
LGTM

2021-07-28 05:47 UTC, merged