refactor(#259): Accept-Language header translations
Dsek-LTH/member-page pull request #344
Opened 2022-01-09 23:09 UTC by emilwihlander

closes #259

2022-02-07 00:02 UTC, oliverlevay requested changes
This is AWESOME! It really makes the gql queries much cleaner. There are some changes I'd like you to make.

2022-02-07 00:02 UTC, oliverlevay commented on frontend/pages/news/article/[id]/edit.tsx
> +    console.log(queryData);
lots of console logs that need to go

2022-11-15 11:20 UTC, oliverlevay commented
I love this PR ! <3 ... but it's hopelessly outdated. The fastest to fix this would proboably be to take inspiration from this code and recreate it. @emilwihlander

2023-05-21 21:00 UTC, danieladugyan commented
> I love this PR ! <3 ... but it's hopelessly outdated. The fastest to fix this would proboably be to take inspiration from this code and recreate it. @emilwihlander

2023-05-21 21:00 UTC, closed without merging