Added translation for committee files
Dsek-LTH/member-page pull request #390
Opened 2022-02-28 12:11 UTC by jacobast

2022-02-28 12:54 UTC, oliverlevay requested changes

2022-02-28 12:54 UTC, oliverlevay commented on frontend/public/locales/en/committee.json
> +  "wipDescription": "Here is text that the comittee can change by themselves!",
committee är felstavat här

2022-03-01 12:02 UTC, LucasBoberg approved these changes
LGTM

2022-03-02 11:19 UTC, oliverlevay approved these changes
LGTM

2022-03-02 11:24 UTC, merged