One Service
Dsek-LTH/member-page pull request #534
Opened 2022-10-21 14:44 UTC by oliverlevay

2022-10-25 22:25 UTC, 01ste02 commented
Jenkins is ready, and after merge we simply need to wait for a test-build to complete before changing the deploy-pipeline and actually pushing to production

2022-10-31 10:19 UTC, LucasBoberg requested changes
I have one comment, that I would like to see changed. And I would like for one more knowledgeable in docker to verify the docker files

2022-10-31 10:40 UTC, 01ste02 reviewed
The dockerfiles look good to me, and are building properly. There remains one issue with the frontend-container not getting env-values from the env-file, but rather relying on a static env-file that is copied on build instead of one that is mounted at runtime. However, that is not related to the dockerfiles.

TLDR; Dockerfiles seem to be OK, and are building

2022-11-01 01:55 UTC, oliverlevay commented on backend/services/core/src/migrator/searchData.ts
> +export default async function meilisearchSeed(knex: any, meilisearch: any) {
> I have one comment, that I would like to see changed. And I would like for one more knowledgeable in docker to verify the docker files

You can take a look, @01ste02 created a sandbox environment based on this branch and everything seems to be working https://member.sandbox.dsek.se/ , I'll fix the types.

2022-11-01 02:03 UTC, oliverlevay commented
> I have one comment, that I would like to see changed. And I would like for one more knowledgeable in docker to verify the docker files

You can take a look, @01ste02 created a sandbox environment based on this branch and everything seems to be working https://member.sandbox.dsek.se/

2022-11-01 12:12 UTC, merged