feature(#72): Added mutations to news service
Dsek-LTH/member-page pull request #88
Opened 2021-03-23 16:12 UTC by LucasBoberg

Closes #72

2021-03-23 18:24 UTC, emilwihlander requested changes
Bra start! La till lite kommentarer om förbättringar och hur du kan komma åt den inloggades member_id.

2021-03-23 18:24 UTC, emilwihlander commented on backend/services/news/src/resolvers.ts
> +    createArticle: ({}, {header, body}: {header: string, body: string}) => {
Lägg till en tredje parameter för att komma åt användaren, mao:
```typescript
//längst upp
import {context} from 'dsek-shared';
//...
createArticle: ({}, {header, body}: {header: string, body: string}, {user}: {user: context.UserContext}) => {
  if (!user) return false;
  return createArticle(header, body);
}
```

2021-03-23 18:24 UTC, emilwihlander commented on backend/services/news/src/resolvers.ts
> +    createArticle: ({}, {header, body}: {header: string, body: string}) => {
Sen kan du skicka med user.keycloak_id createArticle för att skapa en artikel för användaren som är inloggad

2021-03-23 18:24 UTC, emilwihlander commented on backend/services/news/src/db.ts
> +  console.log(result);
Plocka bort denna raden

2021-03-23 18:24 UTC, emilwihlander commented on backend/services/news/src/db.ts
> +const createArticle = async (header: string, body: string) => {
async (header: string, body: string, keycloak_id: string) => {

2021-03-23 18:24 UTC, emilwihlander commented on backend/services/news/src/db.ts
> +  };
```typescript
const {member_id} = (await knex<{keycloak_id: string, member_id: number}>('keycloak').where({keycloak_id}))[0];
```

2021-03-23 19:01 UTC, LucasBoberg commented on backend/services/news/src/typeDefs.ts
> +  createArticle(header: String!, body: String!): Article
Sant att det gör det enklare och är helt ok att ändra på det, hade det så för att jag läst att man ska kunna anropa vilken data som saka retuneras även i mutations. Men kan ändra om det är bättre med att bara retunera bara idet

2021-03-25 17:32 UTC, emilwihlander commented on backend/services/news/package.json
> +    "dev": "ts-node-dev --poll --respawn --transpile-only --watch src src/index.ts",
Remove this!

2021-03-25 21:00 UTC, emilwihlander approved these changes
Ser bra ut!

2021-03-26 06:17 UTC, merged